# Generated by Django 6.0.6 on 2026-06-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelacionDeUnoAMuchos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('movies', models.ManyToManyField(to='RelacionDeUnoAMuchos.movie')),
            ],
        ),
    ]
